name: Code Linting

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.php'
      - 'pint.json'
  pull_request:
    paths:
      - '**.php'
      - 'pint.json'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  php-code-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v4

      - name: Run Pint
        run: vendor/bin/pint --test
